#spring:
#  servlet:
#    multipart:
#      max-file-size: 10MB # 最大文件
#      max-request-size: 50MB # 最大请求
#

#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#
#  redis:
#    database: 0
#    host: 175.178.229.62
#    port: 6379
#    password: admin123
#    timeout: 1000
#    connect-timeout: 500
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
#
#server:
#  port: 8083
#  tomcat:
#    max-http-form-post-size: -1 # 取消最大post上传限制
#    uri-encoding: UTF-8
#
##文件上传目录
#file:
#  store:
#    #    path: /app/files
#    path: F:/files
#


spring:
  servlet:
    multipart:
      max-file-size: 10MB # 最大文件
      max-request-size: 50MB # 最大请求


# 待配置
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  redis:
    database: 0
    host:
    port:
    password:
    timeout: 1000
    connect-timeout: 500
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

server:
  port: 8083
  tomcat:
    max-http-form-post-size: -1 # 取消最大post上传限制
    uri-encoding: UTF-8

#文件上传目录
file:
  store:
    #path: /app/files
    path: E:/test

#机构平台的管理员邮箱：如果有机构申请加入，这两个邮箱会收到审批邮件
fbAdmin:

  email:

system:
  ip: localhost

