spring:
  servlet:
    multipart:
      max-file-size: 10MB # 最大文件
      max-request-size: 50MB # 最大请求

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8083
  tomcat:
    max-http-form-post-size: -1 # 取消最大post上传限制

#文件上传目录
file:
  store:
    path: F:/files

fbAdmin:
  email:
