spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: admin123
    timeout: 1000
    connect-timeout: 500
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

server:
  port: 8084